
name:                implicit-fun-elab
version:             0.1.0.0
# github:              "AndrasKovacs/"
license:             BSD3
author:              "Andr치s Kov치cs"
maintainer:          "puttamalac@gmail.com"
copyright:           "2020 Andr치s Kov치cs"
category:            Language

description:         "Small implementation of elaboration for first-class implicit function types"

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveAnyClass
- EmptyCase
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- LambdaCase
- MultiParamTypeClasses
- NoMonomorphismRestriction
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- Strict
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeInType
- ViewPatterns

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches
- -Wno-partial-type-signatures
- -Wno-unused-imports
- -Wno-type-defaults

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- microlens-platform

source-dirs: .

executable:
  main: Main.hs
  ghc-options:
    - -O
